using cAlgo.API;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;
using static cAlgo.OrderFlowTicksV20;
using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.IO;
using System.Net.Sockets;
using System.Text.Json;
using System.Text;

namespace cAlgo
{
    public partial class OrderFlowTicksV20 : Indicator
    {
        protected override void OnDestroy()
        {
            _Tasks.cts.Cancel();
            if (ProfileParams.EnableFixedRange) {
                foreach (ChartRectangle item in RangeObjs.rectangles)
                    Chart.RemoveObject(item.Name);
            }
        }

        // Code generated by LLM.
        /*
          From my attempts, it should never be declared/invoked in the main thread,
              - ManualResetEventSlim(false) locks the indicator's Initialize, no matter the field or location it's on.

          The idea is "Get any cTrader's object by running BeginInvokeOnMainThread on it"
          The downside is calling it at every cTrader related objects (obviously) (Bars, Chart, etc..)

          A small price to pay to avoid freezes and lags.
        */
        public T GetByInvoke<T>(Func<T> func, string label = null)
        {
            if (func == null) throw new ArgumentNullException(nameof(func));

            T result = default;
            var done = new ManualResetEventSlim(false);

            Stopwatch sw = null;
            if (!string.IsNullOrEmpty(label))
                sw = Stopwatch.StartNew();

            BeginInvokeOnMainThread(() =>
            {
                try {
                    result = func();
                }
                finally {
                    if (!string.IsNullOrEmpty(label)) {
                        sw.Stop();
                        Print($"[GetByInvoke] {label} took {sw.Elapsed.TotalMilliseconds:F2} ms");
                    }
                    done.Set();
                }
            });

            done.Wait(); // wait for main thread to finish
            return result;
        }


        // *********** FIXED RANGE PROFILE ***********
        // LLM code generating was used to quickly get the Drawings (Rectangles/Texts/ControlGrid) logic.
        void RangeInitialize()
        {
            Chart.ObjectsUpdated += OnObjectsUpdated;
            Chart.ZoomChanged += HiddenRangeControls;
        }

        private void OnObjectsUpdated(ChartObjectsEventArgs args)
        {
            if (!ProfileParams.EnableFixedRange)
                return;

            foreach (var rect in RangeObjs.rectangles.ToArray())
            {
                if (rect == null) continue;

                if (rect.IsInteractive)
                    UpdateRectangle(rect);

                if (ShowFixedInfo)
                    UpdateInfoBox(rect);

                UpdateControlGrid(rect);
            }
        }

        private void HiddenRangeControls(ChartZoomEventArgs args)
        {
            foreach (var control in RangeObjs.controlGrids.Values)
                control.IsVisible = args.Chart.ZoomLevel >= FixedHiddenZoom;
        }

        public void CreateNewRange()
        {
            // Use Mini Interval as first X/Y axis
            DateTime lastBarDate = Bars.LastBar.OpenTime;
            int miniIndex = MiniVPs_Bars.OpenTimes.GetIndexByTime(lastBarDate);
            int miniStart = Bars.OpenTimes.GetIndexByTime(MiniVPs_Bars.OpenTimes[miniIndex]);

            string nameKey = $"FixedRange_{DateTime.UtcNow.Ticks}";
            ChartRectangle rect = Chart.DrawRectangle(
                nameKey,
                Bars.OpenTimes[miniStart],
                MiniVPs_Bars.LowPrices[miniIndex],
                lastBarDate,
                MiniVPs_Bars.HighPrices[miniIndex],
                FixedColor,
                2,
                LineStyle.Lines
            );

            rect.IsInteractive = true;
            RangeObjs.rectangles.Add(rect);

            FixedRank.Add(nameKey, new VolumeRankType());

            if (ShowFixedInfo)
                CreateInfoBox(rect);

            CreateControlGrid(rect);
        }

        private void CreateInfoBox(ChartRectangle rect)
        {
            string prefixName = $"{rect.Name}_InfoBox";

            List<ChartText> list = new();
            ChartText fromTxt = Chart.DrawText(prefixName + "_From", "", rect.Time1, rect.Y1, FixedColor);
            ChartText toTxt = Chart.DrawText(prefixName + "_To", "", rect.Time1, rect.Y1, FixedColor);
            ChartText spanTxt = Chart.DrawText(prefixName + "_Span", "", rect.Time1, rect.Y1, FixedColor);

            foreach (ChartText t in new[] { fromTxt, toTxt, spanTxt }) {
                t.FontSize = 11;
                t.VerticalAlignment = VerticalAlignment.Bottom;
                list.Add(t);
            }

            RangeObjs.infoObjects[rect.Name] = list;
            UpdateInfoBox(rect);
        }

        private void CreateControlGrid(ChartRectangle rect)
        {
            Grid grid = new(2, 1)
            {
                Style = Styles.CreateButtonStyle(),
                Margin = 0,
                Height = 75,
                Width = 25,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center
            };

            CheckBox fixCheck = new()
            {
                IsChecked = false,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center
            };
            fixCheck.Click += (s) =>
            {
                bool isFixed = (bool)fixCheck.IsChecked;
                rect.IsInteractive = !isFixed;
                rect.LineStyle = isFixed ? LineStyle.Solid : LineStyle.Lines;
            };

            Button delBtn = new()
            {
                Text = "🗑️",
                Width = 20,
                Height = 20,
                FontSize = 11,
                Padding = 0,
                Margin = "0 0 0 0",
                BackgroundColor = Color.Crimson,
                ForegroundColor = Color.White,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center
            };
            delBtn.Click += (_) => DeleteRectangle(rect);

            grid.AddChild(fixCheck, 0, 0);
            grid.AddChild(delBtn, 1, 0);

            Border border = new()
            {
                Child = grid
            };

            Chart.AddControl(border, rect.Time2, rect.Y2);
            RangeObjs.controlGrids[rect.Name] = border;
        }

        private void UpdateRectangle(ChartRectangle rect)
        {
            DateTime start = rect.Time1 < rect.Time2 ? rect.Time1 : rect.Time2;
            DateTime end = rect.Time1 < rect.Time2 ? rect.Time2 : rect.Time1;

            int startIdx = Bars.OpenTimes.GetIndexByTime(start);
            int endIdx = Bars.OpenTimes.GetIndexByTime(end);
            if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx) return;

            double high = double.MinValue;
            double low = double.MaxValue;
            for (int i = startIdx; i <= endIdx; i++)
            {
                if (Bars.HighPrices[i] > high) high = Bars.HighPrices[i];
                if (Bars.LowPrices[i] < low) low = Bars.LowPrices[i];
            }

            rect.Y1 = high;
            rect.Y2 = low;
            rect.Time1 = Bars.OpenTimes[startIdx];
            rect.Time2 = Bars.OpenTimes[endIdx];

            // Update/Draw
            double bottomY = Math.Min(rect.Y1, rect.Y2);

            ResetFixedRange(rect.Name, end);

            for (int i = startIdx; i <= endIdx; i++)
                VolumeProfile(startIdx, i, ExtraProfiles.Fixed, fixedKey: rect.Name, fixedLowest: bottomY);
        }

        private void UpdateInfoBox(ChartRectangle rect)
        {
            if (!RangeObjs.infoObjects.TryGetValue(rect.Name, out var objs)) return;
            if (objs.Count < 3) return;

            ChartText fromTxt = objs[0];
            ChartText toTxt = objs[1];
            ChartText spanTxt = objs[2];

            DateTime start = rect.Time1 < rect.Time2 ? rect.Time1 : rect.Time2;
            DateTime end = rect.Time1 < rect.Time2 ? rect.Time2 : rect.Time1;
            TimeSpan interval = end.Subtract(start);
            double interval_ms = interval.TotalMilliseconds;

            // Dynamic TimeLapse Format
            string[] interval_timelapse = GetTimeLapse(interval_ms);
            string timelapse_Fmtd = interval_timelapse[0] + interval_timelapse[1];

            int startIdx = Bars.OpenTimes.GetIndexByTime(start);
            int endIdx = Bars.OpenTimes.GetIndexByTime(end);
            if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx) return;

            fromTxt.Text = $"{start:MM/dd HH:mm}";
            toTxt.Text = $"{end:MM/dd HH:mm}";
            spanTxt.Text = timelapse_Fmtd;

            double maxLength = end.Subtract(start).TotalMilliseconds;
            DateTime midTime = start.AddMilliseconds(maxLength / 2);
            double textY = Math.Max(rect.Y1, rect.Y2);

            fromTxt.Time = rect.Time1;
            fromTxt.Y = textY;

            spanTxt.Time = midTime;
            spanTxt.Y = textY;
            spanTxt.HorizontalAlignment = HorizontalAlignment.Center;

            toTxt.Time = rect.Time2;
            toTxt.Y = textY;
            toTxt.HorizontalAlignment = HorizontalAlignment.Left;
        }

        private void UpdateControlGrid(ChartRectangle rect)
        {
            if (!RangeObjs.controlGrids.TryGetValue(rect.Name, out var grid)) return;
            double topY = Math.Max(rect.Y1, rect.Y2);
            DateTime rightTime = rect.Time1 > rect.Time2 ? rect.Time1 : rect.Time2;
            Chart.MoveControl(grid, rightTime, topY);
        }

        public void DeleteRectangle(ChartRectangle rect)
        {
            if (rect == null) return;
            Chart.RemoveObject(rect.Name);
            RangeObjs.rectangles.Remove(rect);

            // remove info objects
            if (RangeObjs.infoObjects.TryGetValue(rect.Name, out var objs))
            {
                foreach (var o in objs)
                    Chart.RemoveObject(o.Name);
                RangeObjs.infoObjects.Remove(rect.Name);
            }

            // remove control grid
            if (RangeObjs.controlGrids.TryGetValue(rect.Name, out var grid))
            {
                Chart.RemoveControl(grid);
                RangeObjs.controlGrids.Remove(rect.Name);
            }

            // remove histograms/lines drawings
            DateTime end = rect.Time1 < rect.Time2 ? rect.Time2 : rect.Time1;
            ResetFixedRange(rect.Name, end);
        }

        private void ResetFixedRange(string fixedKey, DateTime end)
        {
            FixedRank[fixedKey].ClearAllModes();

            int endIdx = Bars.OpenTimes.GetIndexByTime(end);
            int TF_idx = GetSegmentIndex(endIdx);
            
            for (int i = 0; i < segmentsDict[TF_idx].Count; i++)
            {
                switch (GeneralParams.VolumeMode_Input) {
                    case VolumeMode_Data.Normal:    
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Normal");
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Number_Normal");
                        break;
                    case VolumeMode_Data.Buy_Sell:
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Sell");
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Buy");
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Number_Sell");
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Number_Buy");
                        break;
                    default:
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Delta");
                        Chart.RemoveObject($"{fixedKey}_{i}_VP_Fixed_Number_Delta");
                        break;
                }
                // HVN + LVN
                if (NodesParams.EnableNodeDetection) {
                    Chart.RemoveObject($"{fixedKey}_LVN_Low_{i}_Fixed");
                    Chart.RemoveObject($"{fixedKey}_LVN_{i}_Fixed");
                    Chart.RemoveObject($"{fixedKey}_LVN_High_{i}_Fixed");
                    Chart.RemoveObject($"{fixedKey}_LVN_Band_{i}_Fixed");

                    Chart.RemoveObject($"{fixedKey}_HVN_Low_{i}_Fixed");
                    Chart.RemoveObject($"{fixedKey}_HVN_{i}_Fixed");
                    Chart.RemoveObject($"{fixedKey}_HVN_High_{i}_Fixed");
                    Chart.RemoveObject($"{fixedKey}_HVN_Band_{i}_Fixed");
                }
            }

            string[] objsNames = GeneralParams.VolumeMode_Input switch
            {
                VolumeMode_Data.Normal => new string[1] {
                    $"{fixedKey}_VP_Fixed_Normal_Result",
                },
                VolumeMode_Data.Buy_Sell => new string[3] {
                    $"{fixedKey}_VP_Fixed_Sell_Sum",
                    $"{fixedKey}_VP_Fixed_Buy_Sum",
                    $"{fixedKey}_VP_Fixed_BuySell_Result",
                },
                _ => new string[6] {
                    $"{fixedKey}_VP_Fixed_Delta_BuySum",
                    $"{fixedKey}_VP_Fixed_Delta_SellSum",
                    $"{fixedKey}_VP_Fixed_Delta_Result",

                    $"{fixedKey}_VP_Fixed_Delta_MinResult",
                    $"{fixedKey}_VP_Fixed_Delta_MaxResult",
                    $"{fixedKey}_VP_Fixed_Delta_SubResult",
                },
            };

            foreach (string name in objsNames)
                Chart.RemoveObject(name);
        }

        public void ResetFixedRange_Dicts() {
            RangeObjs.rectangles.Clear();
            RangeObjs.infoObjects.Clear();
            RangeObjs.controlGrids.Clear();
        }

    }
}
