using cAlgo.API;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;
using static cAlgo.WeisWyckoffSystemV20;
using System;
using System.Linq;
using System.Globalization;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Text.Json;
using System.Text;

namespace cAlgo
{
    public static class CustomMA
    {
        //  ===== CUSTOM MAS ====
        // MAs logic generated by LLM
        // Modified to handle multiples sources
        // as well as specific OrderFlow() needs.
        public static double StdDev(int index, int Period, double maValue, Dictionary<int, double> buffer)
        {
            double mean = maValue;
            double sumSq = 0.0;
            for (int i = index - Period + 1; i <= index; i++)
            {
                try {
                    double diff = buffer[i] - mean;
                    sumSq += diff * diff;
                } catch {}
            }
            // Sample => (Period - 1) / Population => Period
            return (Period > 1) ? Math.Sqrt(sumSq / (Period - 1)) : 0.0;
        }

        public static double SMA(int index, int period, Dictionary<int, double> buffer)
        {
            if (buffer.Count < period)
                return double.NaN;

            double sum = 0;
            for (int i = index; i > index - period; i--) {
                // The index may jump on Sunday Bars
                try { sum += buffer[i]; } catch { }
            }
            return sum / period;
        }
        public static double EMA(int index, int period, Dictionary<int, double> buffer, Dictionary<int, double> emaDict)
        {
            if (emaDict.Count == 0) {
                emaDict[0] = buffer[index];
                emaDict[1] = buffer[index];
                emaDict[index] = buffer[index];
                return buffer[index];
            }
            double k = 2.0 / (period + 1);
            double value = buffer[index] * k + emaDict[0] * (1 - k);

            if (index != emaDict.Keys.LastOrDefault()) {
                // Always 3
                double prev = emaDict[1];
                emaDict.Clear();
                emaDict[0] = prev;
                emaDict[1] = value;
                emaDict[index] = value; // just to be identified
            } else {
                emaDict[1] = value;
                emaDict[index] = value;
            }
            return value;
        }
        public static double WMA(int index, int period, Dictionary<int, double> buffer, double? overrideLast = null)
        {
            if (buffer.Count < period)
            {
                // not enough values -> average available
                /*
                double sumA = 0;
                for (int i = 0; i <= index; i++) {
                    try { sumA += buffer[i]; } catch { }
                }
                return sumA / available;
                */
                return double.NaN;
            }

            double numerator = 0;
            double denominator = 0;
            int w = 1;
            int start = index - period + 1;
            for (int i = start; i <= index; i++, w++)
            {
                double v = 0;
                try { v = (i == index && overrideLast.HasValue) ? overrideLast.Value : buffer[i]; } catch { }
                numerator += v * w;
                denominator += w;
            }
            return numerator / denominator;
        }
        public static double TMA(int index, int period, Dictionary<int, double> buffer)
        {
            if (period <= 1)
                return buffer[index];

            // need at least 2*period - 1 samples to compute full triangular, otherwise fallback
            if (buffer.Count < 2 * period - 2)
                return double.NaN; // return SMA(index, period, buffer);

            double sumSma = 0.0;
            for (int k = index - period + 1; k <= index; k++)
            {
                double smaK = SMA(k, period, buffer);
                sumSma += smaK;
            }
            return sumSma / period;
        }
        public static double Hull(int index, int period, Dictionary<int, double> buffer)
        {
            if (period < 2) return buffer[index];

            int half = Math.Max(1, period / 2);
            int sqrt = Math.Max(1, (int)Math.Round(Math.Sqrt(period)));

            double wmaHalf = WMA(index, half, buffer);
            double wmaFull = WMA(index, period, buffer);

            double raw = 2 * wmaHalf - wmaFull;
            return WMA(index, sqrt, buffer, raw);
        }
        public static double Wilder(int index, int period, Dictionary<int, double> buffer, Dictionary<int, double> wilderDict)
        {
            if (wilderDict.Count == 0) {
                wilderDict[0] = buffer[index];
                wilderDict[1] = buffer[index];
                wilderDict[index] = buffer[index];
                return buffer[index];
            }
            double value =  (wilderDict[0] * (period - 1) + buffer[index]) / period;

            if (index != wilderDict.Keys.LastOrDefault()) {
                // Always 3
                double prev = wilderDict[1];
                wilderDict.Clear();
                wilderDict[0] = prev;
                wilderDict[1] = value;
                wilderDict[index] = value; // just to be identified
            } else {
                wilderDict[1] = value;
                wilderDict[index] = value;
            }
            return value;
        }
        public static double KAMA(int index, int period, int fast, int slow, Dictionary<int, double> buffer, Dictionary<int, double> kamaDict)
        {
            if (kamaDict.Count == 0) {
                kamaDict[0] = buffer[index];
                kamaDict[1] = buffer[index];
                kamaDict[index] = buffer[index];
                return buffer[index];
            }
            if (buffer.Count < period) return SMA(index, period, buffer);

            double change;
            try { change = Math.Abs(buffer[index] - buffer[index - period]); }
            catch {
                int idxValue = index - period;
                for (int i = idxValue; i < index; i++) {
                    idxValue = i;
                    if (buffer.ContainsKey(i)) break;
                }
                change = Math.Abs(buffer[index] - buffer[idxValue]);
            }

            double volatility = 0.0;
            for (int i = index - period + 1; i <= index; i++) {
                try { volatility += Math.Abs(buffer[i] - buffer[i - 1]); } catch { }
            }

            double er = volatility == 0 ? 0 : change / volatility;
            double fastSC = 2.0 / (fast + 1);
            double slowSC = 2.0 / (slow + 1);
            double sc = Math.Pow(er * (fastSC - slowSC) + slowSC, 2);

            double value = kamaDict[0] + sc * (buffer[index] - kamaDict[0]);

            if (index != kamaDict.Keys.LastOrDefault()) {
                // Always 3
                double prev = kamaDict[1];
                kamaDict.Clear();
                kamaDict[0] = prev;
                kamaDict[1] = value;
                kamaDict[index] = value; // just to be identified
            } else {
                kamaDict[1] = value;
                kamaDict[index] = value;
            }
            return value;
        }
        public static double VIDYA(int index, int period, Dictionary<int, double> buffer, Dictionary<int, double> vidyaDict)
        {
            if (vidyaDict.Count == 0) {
                vidyaDict[0] = buffer[index];
                vidyaDict[1] = buffer[index];
                vidyaDict[index] = buffer[index];
                return buffer[index];
            }

            double cmo = CMO(index, period, buffer);
            // scale factor, tuneable; using 0.2 base as example
            // cTrader uses 0.65 as default
            double alphaBase = 0.65;
            double k = alphaBase * Math.Abs(cmo / 100.0);
            double value = k * buffer[index] + (1 - k) * vidyaDict[0];

            if (index != vidyaDict.Keys.LastOrDefault()) {
                // Always 3
                double prev = vidyaDict[1];
                vidyaDict.Clear();
                vidyaDict[0] = prev;
                vidyaDict[1] = value;
                vidyaDict[index] = value; // just to be identified
            } else {
                vidyaDict[1] = value;
                vidyaDict[index] = value;
            }
            return value;
        }
        public static double CMO(int index, int length, Dictionary<int, double> buffer)
        {
            if (index < 1 || length < 1) return 0.0;
            int start = Math.Max(1, index - length + 1);
            double up = 0, down = 0;
            for (int i = start; i <= index; i++)
            {
                try {
                    double diff = buffer[i] - buffer[i - 1];
                    if (diff > 0) up += diff;
                    else down += -diff;
                } catch { }
            }
            double denom = up + down;
            return denom == 0 ? 0.0 : 100.0 * (up - down) / denom;
        }
    }
}
